### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tchaler2017** [JonHenningsson/iptablesgui#1]
hello, i am getting syntax error when trying to run the code.
the error is : sh: 1: Syntax error: redirection unexpected. i am using pyqt5 and kali linux. thanks
the error is coming from this part :       
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_AddRules(object):
    def Add_Rules_to(self):
        rule = self.textEdit
	rule = str(rule)
	os.system(rule + ' 2> iptables_error.log')
	iptables_error = open('iptables_error.log', 'r')
	error = str(iptables_error.read())
	self.label_3.setText(error)
	iptables_error.close()
        if error == '':
	        iptables_conf = open('iptables.sh','a')
	        iptables_conf.write(rule + '\n')
	        iptables_conf.close()

**Comment by JonHenningsson** [comment]
Hi,

I haven't worked on this project for many years and it's only been tested with python 2.7 and PyQt4. I can try to make it work but I suggest you check for other alternatives..

**Comment by JonHenningsson** [comment]
Python 3 with PyQt5 done

**Comment by tchaler2017** [comment]
Thanks bro, is working now. the problem was "textEdit" (rule = self.textEdit) in my code.
